# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - develop
    - master

pool:
  name: 'eBukett'

workspace:
  clean: all

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

#
# TODO ved nye prosjekter: justere etter behov, navn og plassering pr prosjekt må endres herfra og ned
#

steps:
- task: qetza.replacetokens.replacetokens-task.replacetokens@3
  displayName: 'Replace tokens in **/environment.ts,  **/environment.test.ts, **/environment.prod.ts'
  inputs:
    targetFiles: |
     **/environment.ts
     **/environment.test.ts
     **/environment.prod.ts
    writeBOM: false
    enableTelemetry: false

- task: NuGetInstaller@0
  displayName: 'NuGet restore'
  inputs:
    solution: LabKost.sln
    nuGetRestoreArgs: '-source "https://api.nuget.org/v3/index.json"'
    verbosity: Detailed

- task: Npm@1
  displayName: 'npm install'
  inputs:
    workingDir: LabKost-web
    verbose: true

# - task: CmdLine@1
#   displayName: 'Retire.js'
#   inputs:
#     filename: cmd.exe
#     arguments: '/c "retire --proxy http://proxy.ihelse.net:3128 --ignorefile ../.retireignore.json"'
#     workingFolder: LabKost-web
#     continueOnError: true

- task: Npm@1
  displayName: 'npm build LabKost-web'
  inputs:
    command: custom
    workingDir: LabKost-web
    verbose: true
    customCommand: 'run build --c="production"'

# - task: ArchiveFiles@2
#   displayName: 'Archive LabKost-Web/dist/LabKost-Web'
#   inputs:
#     rootFolderOrFile: 'LabKost-Web/dist/LabKost-Web'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)/LabKost-Web/dist/'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/'
    OverWrite: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: LabKost-Web'

- task: DotNetCoreCLI@2
  displayName: Build and Publish web app API
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/API.csproj'
    inlineScript: |
              Write-Host "WorkingDirectory: $(Build.ArtifactStagingDirectory)"
    arguments: -o $(Build.ArtifactStagingDirectory) --configuration Release
    zipAfterPublish: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: LabKost'

# - task: sonarsource.sonarqube.6D01813A-9589-4B15-8491-8164AEB38055.SonarQubeAnalyze@4
#   displayName: 'Run Code Analysis'

# - task: sonarsource.sonarqube.291ed61f-1ee4-45d3-b1b0-bf822d9095ef.SonarQubePublish@4
#   displayName: 'Publish Quality Gate Result'
