name: Login in to Azure environment
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
    checkout:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
    login-dev:
        runs-on: ubuntu-latest
        steps:
            - name: DEV environment login    
              if: ${{inputs.environment == 'DEV'}}      
              uses: azure/login@v1
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID_DEV}}
                tenant-id: ${{ secrets.AZURE_TENANT_ID_DEV }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID_DEV }}
    login-qa:
        runs-on: ubuntu-latest
        steps:
            - name: QA environment login
              if: ${{inputs.environment == 'QA'}}      
              uses: azure/login@v1
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID_QA}}
                tenant-id: ${{ secrets.AZURE_TENANT_ID_QA }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID_QA }}
    login-prod:
        runs-on: ubuntu-latest
        steps:
            - name: PROD environment login
              if: ${{inputs.environment == 'PROD'}}      
              uses: azure/login@v1
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID_PROD}}
                tenant-id: ${{ secrets.AZURE_TENANT_ID_PROD }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID_PROD }}
