# Workflow for å bygge og uploade en angular app som artifact for senere bruk i deploy
# Slik denne fungerer nå forventer den at det er en mappe som heter dist i working-directory hvor output av npm run build blir lagret
# Denne mappen blir så zippet og lastet opp som artifact som heter angular-app og kan hentes i neste jobb

name: Build angular app with node
on:
  workflow_call:
    inputs:
      app-name:
        required: true
        type: string
      node-version:
        required: true
        type: string
      working-directory:
        required: true
        type: string
      output-path:
        required: true
        type: string    
  
jobs:
  sonarcloud:
    runs-on: HVI-SKY-TJENESTER-RUNNER  
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v3.0.0
        with:
          args: >
            -Dsonar.qualitygate.wait=true
            -Dsonar.organization='Helse%20Vest%20IKT'
            # -Dsonar.projectKey='Hviktor'
            # -Dsonar.branch.name=${{ github.ref }}
        env: 
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        
  build:
    runs-on: HVI-SKY-TJENESTER-RUNNER
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'npm'
          cache-dependency-path: '${{ inputs.working-directory }}/package-lock.json'

      - name: npm install, build, and test
        working-directory: '${{ inputs.working-directory }}'
        run: |
          npm install
          npm run build --if-present
          #npm run test --if-present # må ha chrome installert???

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4 #v4 virker på ubuntu-latest og self-hosted Linux, IKKE windows
        with:
          name: ${{inputs.app-name}}
          path: '${{ inputs.working-directory }}/${{ inputs.output-path }}'
          compression-level: 0            # 9 er maks, 1 er min og 0 er ingen. Er satt til 0 for den er kjappest
  