# an action that can be called by another workflow file
on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        cache-dependency-path: ./Hviktor-web/package-lock.json
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: npm install, build, and test
      working-directory: ./Hviktor-web
      run: |
        npm install
        npm run build --if-present
