# Logger på azure med oidc og kjører en bicep-fil som konfigurerer azure-ressurser

name: Azure Environment Configuration Workflow
on:
  workflow_call:

jobs:
  configure-azure:
    runs-on: ubuntu-latest      
    steps:
    - uses: actions/checkout@v4
    - uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID_DEV }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID_DEV }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID_DEV }}        
    - uses: azure/cli@v2
      with:
        inlineScript:        
          #!/bin/bash
          az group create --name 'HVI-UTV-Hviktor-GH-rg' --location norwayeast          
        
      
    - uses: azure/arm-deploy@v2
      with:
        template: 'AzurePipelineTools/azure-config.bicep'
        parameters: 'AzurePipelineTools/azure-config.parameters.json'
        deploymentMode: 'Complete'
        scope: 'subscription'
        resourceGroupName: 'HVI-UTV-Hviktor-GH-rg' #kun for subscription
        failOnStdErr: false
        region: 'norwayeast'
        additionalArguments: '--verbose'
