# Logger på azure med oidc og kjører en bicep-fil som konfigurerer azure-ressurser

name: Azure Environment Configuration Workflow
on:
  workflow_call:
    inputs:
      client_id:
        required: true
        type: string
      tenant_id:
        required: true
        type: string
      subscription_id:
        required: true
        type: string
      node-version:
        required: true
        type: string
jobs:
  print-variables:
    runs-on: ubuntu-latest
    steps:
    - name: Print variables
      run: |
        echo "Client ID: ${{ inputs.client_id }}"
        echo "Tenant ID: ${{ inputs.tenant_id }}"
        echo "Subscription ID: ${{ inputs.subscription_id }}"
        echo "Node Version: ${{ inputs.node-version }}"
  configure-azure:
    runs-on: self-hosted-windows      
    steps:
    - uses: actions/checkout@v4
    - uses: azure/login@v1
      with:
        client-id: ${{ inputs.client_id }}
        tenant-id: ${{ inputs.tenant_id }}
        subscription-id: ${{ inputs.subscription_id }}
      
    - uses: azure/arm-deploy@v1
      with:
        template: 'AzurePipelineTools/azuredeploy.bicep'
        #parameters: 'AzurePipelineTools/azuredeploy.parameters.json'
        deploymentMode: 'Incremental'
        scope: 'subscription'
        region: 'Norway East'
