# Logger på azure med oidc og kjører en bicep-fil som konfigurerer azure-ressurser

name: Azure Environment Configuration Workflow
on:
  workflow_call:

jobs:
  configure-azure:
    runs-on: self-hosted-windows      
    steps:
    - uses: actions/checkout@v4
    - uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID_DEV }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID_DEV }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID_DEV }}
      
    - uses: azure/arm-deploy@v1
      with:
        template: 'AzurePipelineTools/azuredeploy.bicep'
        #parameters: 'AzurePipelineTools/azuredeploy.parameters.json'
        deploymentMode: 'Incremental'
        scope: 'subscription'
        region: 'Norway East'
