# download artifact from build job and deploy to Azure WebApp
on:
    workflow_call:

jobs:
    azure-login:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - uses: azure/login@v1
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID_DEV }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID_DEV }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID_DEV }}                

    download-artifact:
        runs-on: ubuntu-latest
        steps:
            - name: Download artifact from build job
              uses: actions/download-artifact@v4
              with:
                name: angular-app
            - name: Deploy webapp
              uses: azure/webapps-deploy@v3
              with:
                app-name: HviktorDev
                package: './'
          
