name: "Deploy til miljø"
on:
  workflow_call:
    inputs:
      environment:
        description: "Environment man vil deploye til"
        required: true
        type: string
      ekstern-tilgang:
        description: "Ekstern tilgang"
        required: false
        type: boolean
        default: false
jobs:  
  build-frontend:
    name: 'Build Angular app'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: hviktor-angular
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: 'hviktor-angular/package-lock.json'

      - name: Install
        run: npm ci --ignore-scripts

      - name: Build
        run: ng build --configuration production
      
      - name: Copy web.config to build folder
        run: cp web.config dist/hviktor

      - name: Upload artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: 'web-${{ inputs.environment }}'
          path: 'hviktor-angular/dist/hviktor'
          compression-level: 0

  provision-app-service-angular:
    name: "Provision angular app service"
    needs: [build-frontend]
    uses: HelseVestIKT/HVI-Felles-WorkFlows/.github/workflows/provision-app-service.yaml@v2.0.3
    secrets: inherit
    with:
      environment: ${{ inputs.environment }}
      artifact-name: 'web'
      ekstern-tilgang: ${{ inputs.ekstern-tilgang }}      
    permissions:
      contents: read
      id-token: write  

  deploy-angular-app:
    needs: [build-frontend, provision-app-service-angular]
    uses: HelseVestIKT/HVI-Felles-WorkFlows/.github/workflows/deploy-angular-app.yaml@v2.0.11    
    with:
      environment: ${{ inputs.environment }}
      artifact-name: 'web'
    secrets: inherit
    permissions:
      contents: read
      id-token: write