# workflow som kan kalles og gjør download artifact og deploy til azure
on:
    workflow_call:
      inputs:
        artifact-name:
          required: true
          type: string
        webapp-name:
          required: true
          type: string
        environment: 
          required: true
          type: string

jobs:
    configure-azure:
        runs-on: HVI-SKY-TJENESTER-RUNNER               
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
              # Må bruke if-statement for å kunne logge på riktig subscription basert på input-parameter. Eneste måten jeg har funnet så langt.
              # Prøvde med legge ting i en egen workflow som slo sammen navn med miljø og prøvd å hente
            - name: configure
              uses: ./.github/workflows/configure-azure-env.yml
              with:
                environment: ${{inputs.environment}}
    deploy-to-azure:
        runs-on: HVI-SKY-TJENESTER-RUNNER               
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
              # Må bruke if-statement for å kunne logge på riktig subscription basert på input-parameter. Eneste måten jeg har funnet så langt.
              # Prøvde med legge ting i en egen workflow som slo sammen navn med miljø og prøvd å hente ut secrets, men det var nytteløst. 
              # Duplisering må dessverre brukes om ikke vi finner på noe lurt

            - name: DEV environment login    
              if: ${{inputs.environment == 'DEV'}}      
              uses: azure/login@v1
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID_DEV}}
                tenant-id: ${{ secrets.AZURE_TENANT_ID_DEV }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID_DEV }}
        
            - name: QA environment login
              if: ${{inputs.environment == 'QA'}}      
              uses: azure/login@v1
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID_QA}}
                tenant-id: ${{ secrets.AZURE_TENANT_ID_QA }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID_QA }}
                  
            - name: PROD environment login
              if: ${{inputs.environment == 'PROD'}}      
              uses: azure/login@v1
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID_PROD}}
                tenant-id: ${{ secrets.AZURE_TENANT_ID_PROD }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID_PROD }}
        
            - name: Download artifact from build job
              uses: actions/download-artifact@v4
              with:
                name: ${{ inputs.artifact-name }}

            - name: Deploy webapp
              uses: azure/webapps-deploy@v3
              with:
                app-name: ${{ inputs.webapp-name }}
                package: './'
          
