# workflow som kan kalles og gjør download artifact og deploy til azure
on:
    workflow_call:
      inputs:
        artifact-name:
          required: true
          type: string
        webapp-name:
          required: true
          type: string  

jobs:
    deploy-to-azure:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Azure login
              uses: azure/login@v1
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID_DEV }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID_DEV }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID_DEV }}                

            - name: Download artifact from build job
              uses: actions/download-artifact@v4
              with:
                name: ${{ inputs.artifact-name }}

            - name: Deploy webapp
              uses: azure/webapps-deploy@v3
              with:
                app-name: ${{ inputs.webapp-name }}
                package: './'
          
