#hovedfil for applikasjonen. Gjør bruk av workflows/actions for å bygge, konfigurere og deploye applikasjonen til Azure
on:
  push:
    branches: [ "main", "develop"] # Kjører ved push til main eller develop branch
  workflow_dispatch: # Tillater manuell kjøring av workflow 
    

env:
  AZURE_WEBAPP_NAME: Hviktor    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '20.x'  # set this to the node version to use
  ANGULAR-APP: 'hviktor-angular' # set this to the name of the angular app
  ENVIRONMENT: 'DEV' # set this to the environment you are deploying to

permissions:
  contents: read
  id-token: write

jobs:
  # fancy måte å sende env variables til neste reusable workflow: https://www.sethduke.io/github-reusable-workflows-environment-variables-workaround/
  variables:
    runs-on: ubuntu-latest
    steps: [run: echo]
    outputs: 
      node-version: ${{ env.NODE_VERSION }}
      webapp-name: ${{ env.AZURE_WEBAPP_NAME }}
      angular-app: ${{ env.ANGULAR-APP }}
      environment: ${{ env.ENVIRONMENT }}

  build-angular-app:
    needs: variables
    uses: ./.github/workflows/wf-modules/build-angular-app.yml
    with:
      working-directory: './Hviktor-web'
      node-version: ${{needs.variables.outputs.node-version}}
      app-name: ${{needs.variables.outputs.angular-app}} # må stemme overens med navn til f.eks. deploy
      # må stemme overens med output-path i angular.json
      output-path: 'dist'

# # denne hører egentlig til i scriptet, altså. bør inn i build-angular-app.yml
# # npm run test --if-present

  configure-azure-env:  
    needs: variables
    uses: ./.github/workflows/wf-modules/configure-azure-env.yml
    with:
      environment: ${{needs.variables.outputs.environment}}
    secrets: inherit

  deploy:
    needs: [build-angular-app, configure-azure-env,variables]
    uses: ./.github/workflows/wf-modules/deploy-app-to-azure.yml
    secrets: inherit
    with:
      artifact-name: ${{needs.variables.outputs.angular-app }}
      webapp-name: ${{needs.variables.outputs.webapp-name}}
      environment: ${{needs.variables.outputs.environment}}
