name: Node.js Setup and Build Workflow
on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
      working-directory:
        required: true
        type: string    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: '${{ inputs.working-directory }}/package-lock.json'

      - name: npm install, build, and test
        working-directory: '${{ inputs.working-directory }}'
        run: |
          npm install
          npm run build:prod --if-present
      - name: List files
        run: ls -R

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4 #v4 virker på ubuntu-latest og self-hosted Linux, IKKE windows
        with:
          name: node-app
          path: '${{ inputs.working-directory }}/dist/Hviktor-web'
          compression-level: 0            # 9 er maks, 1 er min og 0 er ingen. Er satt til 0 for den er kjappest
  