name: Node.js Setup and Build Workflow
on:
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: './Hviktor-web/package-lock.json'

      - name: npm install, build, and test
        working-directory: './Hviktor-web'
        run: |
          npm install
          npm run build --if-present